Add request using relationships between tables
Grandi0z/vet_clinic_database pull request #4
Opened 2023-09-01 20:11 UTC by Grandi0z

### This pull request adds requests using relationships between tables : 
#### Change made : 
- Add `vets` table
- Add join tables `specializations` and `visits`
- Insert data
- Add queries using primary key & foreign key mechanisms for joining tables and relationships between tables

#### Note: Here are the results of added queries

1. 
![req1](https://github.com/Grandi0z/vet_clinic_database/assets/114248080/d24cf5b3-a2f5-477a-ba74-e00021be75cb)

2. 
![req2](https://github.com/Grandi0z/vet_clinic_database/assets/114248080/f73d9671-f101-4f1e-9b08-5e8b58adf5ab)

2023-09-01 20:35 UTC, 1GORDON requested changes
##
## Hi @Grandi0z ✋

Good job so far!

## Highlights!
- Created visits table ✔️ 
- Created specialization table ✔️
- Created vets table ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 20:35 UTC, 1GORDON commented on schema.sql
> +    PRIMARY KEY(animals_id, vets_id, date));
Great job @Grandi0z 🤝

- [ ] As stated in the project requirements, kindly ensure to add the `visit_date` column to the `visits` table so as to track the date of the visit.

2023-09-01 20:35 UTC, 1GORDON commented on data.sql
Great job @Grandi0z 🤝

- [ ] As stated in the project requirements, kindly add data for the `vets` table, `specialization` table, and `visits` table to the `data.sql` file.
- [ ] As stated in the project requirements, kindly create queries to answer questions in
transactions. Kindly add these queries to the `queries.sql` file.

2023-09-02 19:15 UTC, tugsem approved these changes
## STATUS: APPROVED 👍🎯  
Hello @Grandi0z  👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ Required changes implemented
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 19:53 UTC, merged